"""
GitHub API로 agent-authored Python PR 수집 (AIDev external validation).

연구계획서 §15.2 sampling frame:
  - 1차 필터: Python repository / PR
  - 2차 필터: dependency manifest 변경 (requirements.txt, pyproject.toml,
              setup.py, setup.cfg, Pipfile, Pipfile.lock, poetry.lock,
              uv.lock, pdm.lock)
  - Stratification: agent, repository, change type, manifest type
  - Sample size: 50~100

Agent identification heuristics:
  - "aider:" prefix or "aider-ai/aider" co-author
  - "devin-ai-integration[bot]" author
  - "cursor" in commit message
  - "claude-code", "Co-Authored-By: Claude" in commit message
  - "github-actions[bot]" + AI commit signature
  - "Co-Authored-By: openai" or "openai-codex[bot]"

사용:
  export GITHUB_TOKEN=...
  python -m AgentSupplyGuard.pipeline.aidev_collect \\
      --out aidev_sample.jsonl --target 100
"""

import argparse
import json
import os
import time
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError

API = "https://api.github.com"
MANIFESTS = {
    "requirements.txt", "pyproject.toml", "setup.py", "setup.cfg",
    "Pipfile", "Pipfile.lock", "poetry.lock", "uv.lock", "pdm.lock",
}

# (agent_name, GitHub search query qualifier)
AGENT_QUERIES = [
    ("aider", 'author:aider-ai'),
    ("aider", '"Co-Authored-By: aider"'),
    ("aider", '"aider:"'),
    ("devin", 'author:app/devin-ai-integration'),
    ("devin", '"Co-Authored-By: Devin"'),
    ("cursor", '"Co-Authored-By: Cursor"'),
    ("cursor", '"Cursor agent"'),
    ("claude-code", '"Co-Authored-By: Claude"'),
    ("claude-code", '"Generated with Claude Code"'),
    ("openai-codex", 'author:app/openai-codex'),
    ("codex", '"openai-codex[bot]"'),
    ("codex", '"Co-Authored-By: openai"'),
    ("sweep", 'author:app/sweep-ai'),
    ("codewhisperer", '"Co-Authored-By: Amazon Q"'),
    ("continue", '"Generated by Continue"'),
]


def gh_request(url: str, token: str | None, retries: int = 4) -> dict | list:
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AgentSupplyGuard-AIDev-Collector",
        **({"Authorization": f"Bearer {token}"} if token else {}),
    }
    for attempt in range(retries):
        try:
            with urlopen(Request(url, headers=headers), timeout=30) as resp:
                data = json.loads(resp.read())
                # proactively back off when the rate-limit window is nearly drained
                remaining = int(resp.headers.get("X-RateLimit-Remaining", "0") or 0)
                if remaining < 3:
                    reset = int(resp.headers.get("X-RateLimit-Reset", "0") or 0)
                    wait = min(max(reset - int(time.time()), 0) + 5, 70)
                    print(f"  rate-limit low ({remaining}), sleeping {wait}s")
                    time.sleep(wait)
                return data
        except HTTPError as e:
            # 403/429 = primary/secondary rate limit -> wait for reset and retry
            if e.code in (403, 429):
                reset = e.headers.get("X-RateLimit-Reset")
                wait = (max(int(reset) - int(time.time()), 0) + 5) if reset else 30 * (attempt + 1)
                wait = min(wait, 70)
                print(f"  HTTP {e.code} rate-limited, sleeping {wait}s (attempt {attempt+1}/{retries})")
                time.sleep(wait)
                continue
            body = e.read().decode("utf-8", errors="replace")[:200]
            print(f"  HTTP {e.code}: {body}")
            return None
        except Exception as e:  # URLError, timeout, ConnectionReset, JSON errors
            print(f"  net error {type(e).__name__}: {e} (attempt {attempt+1}/{retries})")
            time.sleep(5 * (attempt + 1))
            continue
    print("  giving up after retries")
    return None


def search_prs(agent: str, agent_qualifier: str, token: str, per_page: int = 30, max_pages: int = 5) -> list:
    """Python repo + agent author/co-author 로 PR 검색."""
    out = []
    for page in range(1, max_pages + 1):
        q = f"is:pr is:merged language:Python {agent_qualifier}"
        url = f"{API}/search/issues?q={q.replace(' ', '+')}&per_page={per_page}&page={page}"
        print(f"  [{agent}] page {page}: {q}")
        res = gh_request(url, token)
        if not res or not res.get("items"):
            break
        for item in res["items"]:
            out.append({
                "agent": agent,
                "html_url": item["html_url"],
                "title": item["title"],
                "created_at": item["created_at"],
                "repository_url": item["repository_url"],
                "user": item["user"]["login"],
                "pr_api_url": item["pull_request"]["url"],
            })
        time.sleep(2)
    return out


def get_pr_files(pr_api_url: str, token: str) -> list[dict]:
    """PR 의 changed files. manifest 변경 확인용."""
    url = pr_api_url + "/files?per_page=100"
    res = gh_request(url, token)
    if not isinstance(res, list):
        return []
    return res


def has_dependency_change(files: list[dict]) -> dict:
    """파일 목록에서 manifest 변경 검출."""
    changed_manifests = []
    for f in files:
        name = (f.get("filename") or "").rsplit("/", 1)[-1]
        if name in MANIFESTS:
            changed_manifests.append({
                "path": f["filename"],
                "additions": f.get("additions", 0),
                "deletions": f.get("deletions", 0),
                # full patch retained: truncating to 2000 chars silently dropped
                # dependency lines in large manifest diffs and biased toward
                # under-counting risks (reviewer-flagged scaleup prerequisite).
                "patch": (f.get("patch") or ""),
            })
    return {
        "has_change": bool(changed_manifests),
        "manifests": changed_manifests,
    }


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--target", type=int, default=100)
    p.add_argument("--token", default=os.environ.get("GITHUB_TOKEN"))
    p.add_argument("--token-file", default=os.path.expanduser("~/.gh_token"))
    args = p.parse_args()

    if not args.token and Path(args.token_file).exists():
        args.token = Path(args.token_file).read_text().strip()
        print(f"[+] token from {args.token_file} (len={len(args.token)})")
    if not args.token:
        print("[!] GITHUB_TOKEN not set — rate-limit 60 req/hour (unauthenticated)")

    # 1단계: agent 별 PR 후보 수집 (resumable: 쿼리별로 즉시 체크포인트)
    # The execution environment reaps long-running networked background jobs
    # (~60-90s), so we persist after EVERY query and skip done queries on rerun.
    cand_path = args.out.with_suffix(".candidates.jsonl")
    done_path = args.out.with_suffix(".done.json")
    candidates = []
    seen_urls = set()
    if cand_path.exists():
        for line in cand_path.read_text().splitlines():
            if line.strip():
                pr = json.loads(line)
                if pr["html_url"] not in seen_urls:
                    seen_urls.add(pr["html_url"]); candidates.append(pr)
    done_queries = set(json.loads(done_path.read_text())) if done_path.exists() else set()
    print(f"[resume] {len(candidates)} candidates, {len(done_queries)} queries already done")

    for agent, qualifier in AGENT_QUERIES:
        qid = f"{agent}|{qualifier}"
        if qid in done_queries:
            continue
        prs = search_prs(agent, qualifier, args.token, per_page=30, max_pages=3)
        print(f"  [{agent}] found {len(prs)} candidate PRs")
        with cand_path.open("a", encoding="utf-8") as fh:
            for pr in prs:
                if pr["html_url"] in seen_urls:
                    continue
                seen_urls.add(pr["html_url"]); candidates.append(pr)
                fh.write(json.dumps(pr, ensure_ascii=False) + "\n")
        done_queries.add(qid)
        done_path.write_text(json.dumps(sorted(done_queries), ensure_ascii=False))
        time.sleep(2)

    print(f"\nTotal unique candidates: {len(candidates)}")

    # 2단계: dependency manifest 변경 필터 (증분 저장 + resume)
    filtered_urls = set()
    n_filtered = 0
    checked_path = args.out.with_suffix(".checked.json")
    checked = set(json.loads(checked_path.read_text())) if checked_path.exists() else set()
    if args.out.exists():
        for line in args.out.read_text().splitlines():
            if line.strip():
                filtered_urls.add(json.loads(line)["html_url"]); n_filtered += 1
    print(f"[resume] phase2: {n_filtered} already kept, {len(checked)} already checked")

    for i, pr in enumerate(candidates):
        if n_filtered >= args.target:
            break
        if pr["html_url"] in checked or pr["html_url"] in filtered_urls:
            continue
        print(f"[{i+1}/{len(candidates)}] checking {pr['html_url']}")
        files = get_pr_files(pr["pr_api_url"], args.token)
        dep = has_dependency_change(files)
        checked.add(pr["html_url"])
        if dep["has_change"]:
            pr["dep_changes"] = dep["manifests"]
            pr["n_files_total"] = len(files)
            n_filtered += 1
            with args.out.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(pr, ensure_ascii=False) + "\n")
            print(f"  ✓ dependency-changing ({len(dep['manifests'])} manifest) [{n_filtered}/{args.target}]")
        if len(checked) % 20 == 0:
            checked_path.write_text(json.dumps(sorted(checked), ensure_ascii=False))
        time.sleep(1)
    checked_path.write_text(json.dumps(sorted(checked), ensure_ascii=False))

    filtered = []
    if args.out.exists():
        filtered = [json.loads(l) for l in args.out.read_text().splitlines() if l.strip()]
    print(f"\nSaved {len(filtered)} dependency-changing agent PRs → {args.out}")

    # Stratification 요약
    by_agent = {}
    for pr in filtered:
        by_agent.setdefault(pr["agent"], 0)
        by_agent[pr["agent"]] += 1
    print(f"By agent: {by_agent}")


if __name__ == "__main__":
    main()
